In [5]:
import torch

In [16]:
x=torch.arange(12)  #创建一个行向量包含以0开始的前12个整数
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x.numel()  #元素总数

12

In [18]:
x.shape  #访问张量的形状

torch.Size([12])

In [19]:
x.numel()

12

In [20]:
X=x.reshape(3,4)  #把张量x从形状为(12,)的行向量转换为形状为(3,4)的矩阵

In [21]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [22]:
torch.zeros(2,3,4)  #创建形状为(2,3,4)的张量并且所有元素置为0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
torch.ones(2,3,4)  #创建形状为(2,3,4)的张量并且所有元素置为1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3,4)  #随机初始化参数的值创建形状为(3,4)的张量，每个元素都从均值为0标准差为1的高斯分布中随机采样

tensor([[-1.2099,  1.0301,  0.3968, -0.6502],
        [-0.9396,  0.6907, -0.3685, -0.9984],
        [ 0.0410,  0.6808,  0.4279, -1.5315]])

In [15]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])  #创建张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [24]:
x=torch.tensor([1.0,2,4,8])  #具有相同形状的张量，按元素运算
y=torch.tensor([2,2,2,2,])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [25]:
torch.exp(x)  #求幂

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [46]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)     #沿行连结dim=0沿列连结dim=1

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [49]:
X<Y  #判断X,Y对应位置元素是否相等

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
X.sum()  #对张量的所有元素求和，会产生一个单元素张量

tensor(66.)

In [54]:
#广播机制
a=torch.arange(6).reshape(3,1,2)  #创建两个张量
b=torch.arange(4).reshape(1,2,2)
a,b

(tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]]]),
 tensor([[[0, 1],
          [2, 3]]]))

In [55]:
a+b  #a,b形状不匹配，a+b时将两个矩阵广播为一个3x2的矩阵，矩阵a将复制列，矩阵b将复制行

tensor([[[0, 2],
         [2, 4]],

        [[2, 4],
         [4, 6]],

        [[4, 6],
         [6, 8]]])

In [34]:
#索引和切片
X[-1],X[1:3]  #选择X的最后一个元素；和第二个和第三个元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [36]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [38]:
#节省内存
before=id(Y)
Y=Y+X         #Python先计算的Y+X为结果分配新的内存，然后使Y指向内存中的这个位置
id(Y)==before

False

In [39]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 2346741560752
id(Z): 2346741560752


In [40]:
before=id(X)
X+=Y         #使用X+=Y或X[:]=X+Y减少内存开销
id(X)==before

True

In [41]:
#转换为其他的Python对象
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)  #将大小为1的张量转换为Python标量可以调用item函数

(tensor([3.5000]), 3.5, 3.5, 3)